version: '3.3'
services:
  db:
    image: arm64v8/mysql:oracle
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE=intro
  docker-demo:
    image: luchob/docker-demo:v2
    ports:
      - "8080:8080" # web ui
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root